language: node_js
node_js:
- "4.3"
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/zachlysobey/react-playground.git
  - secure: "QLRKBnPrGV6YyoGKtDMnJaOUvgFqqL+UGRn8Y9ibFNRXNyGRA37hrTCSgqt/XZgJYbS/hroiM7LPAYaAKN2Nqkvk59nnxjLrVT2/VgWMTdo6OWbqAi+h2HL0Bw9T544IWmz9CA7IRHAdGidcVf7LSlPF9HKQX5MCpfL4VNuf0ASHEFRVuulC5IiMIv4Xaj4cOnLvUEKYRIzSMHQ/h/0zinXCxWmCTza6iEtQrRh3x1ZgfkN+VB9Kq7/3sfkIm+ALfYw/hUE24rD4UnSKJaIoIrnJtGl7bVnu1v9J3jJVfU4Cj936cx/DhoUWGxOMgwEyFtvwulnQrkqfSTziaPfmVorGeeoiDWHilLg/oNYWTg5KpxjwxpkkTZ5b3NKNKjFmQGT+lJnuolMYOsYkIuQrU68J9uD2sMge5wx0WCCLDfRcDs97HpPPLCho3TtY1qWiTbH2sDfUVxrnxfCV41uZqncL4d89NK0yU4dltzg0Paw5eRvw9kVOvn7gwpegJ7BqkJBk2Uv0mFf01NROPfzfrGjTPYpq/iBoryuhcEWH3yPmoorm/BpRf0ZMOyRF64cfC+RcWJalayVyJtp7veMnQcJ0M43CDFBoos5ekahl9bnhNMwVaKpJ7OoZmmyjEg7Y0d2bIyy3MZfV0pptOzztnJShu1izy/4DNIR3LrvH/QE="
